### ISSUE TITLE
仿真数据集运行结果

### ISSUE THREAD

**Issue by zlyrs1** [danfenghong/IEEE_TNNLS_EGU-Net#5]
![image](https://user-images.githubusercontent.com/27490404/140940591-f5508340-6896-41b9-adfe-78d416dc4ccc.png)
您好，这是我在仿真数据集(提供的pure和mixed)上运行EGU-Net-pw.py得到的结果，为什么跑出来是损失下降了，但是准确度也跟着下降而且很低呢

**Comment by danfenghong** [comment]
你好，解混不是分类，解混是为了得到丰度图，然后计算估计的丰度图和真实图间的误差，所以acc也是减低了，说明越接近真是图。

zlyrs1 ***@***.***> 于2021年11月9日周二 下午11:15写道：

**Comment by zlyrs1** [comment]
谢谢您的解答，明白了
