### ISSUE TITLE
How to test on my data?

### ISSUE THREAD

**Issue by jikerWRN** [danfenghong/IEEE_TNNLS_EGU-Net#8]
Hi, 
thanks for your good work!

I want to know may i test the model on my data? 

look forward to your reply！

**Comment by danfenghong** [comment]
yes, of course. You can take place of the given example data with your own
data.

jikerWRN ***@***.***> 于2022年1月15日周六 16:58写道：

**Comment by jikerWRN** [comment]
Thanks!
